site_name: PRSice-2
repo_url: https://github.com/choishingwan/PRSice
site_author: Shing Wan CHOI
nav:
    - index.md
    - Quick Start:
        - PRSice: quick_start.md
        - PRSet: quick_start_prset.md
        
    - Detail Guides:
        - PRSice: step_by_step.md
        - PRSet: prset_detail.md

    - Available Commands: command_detail.md

    - Developers:
        - Compile from Source: compilation.md
        - Development Decisions: decisions.md
        - Useful Resources: resources.md

    - Misc:
        - Additional Steps for MAC and Window users: extra_steps.md
        - Frequently Asked Questions: faq.md
        - Archive: archive.md

theme: readthedocs
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - toc:
        permalink: True
    - codehilite
    - pymdownx.arithmatex:
        generic: True
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret

extra_css:
  - css/extra.css

google_analytics:
    - 'UA-113286405-1'
    - auto

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
